### ISSUE TITLE
enable-circe-highlight-all-nicks should use existing colors

### ISSUE THREAD

**Issue by naclander** [emacs-circe/circe#317]
Currently `circe-highlight-all-nicks` highlights the nicks as green, if it is enabeld.

I think it would be nice to also have the option to, instead of green, set the highlight color the same as the already-highlighted nick. This way the colors are kept consistent, and I can see who is replying to who simply by the color in the messages.

**Comment by wasamasa** [comment]
Does customizing either face to be the same as the other one solve your problem?

**Comment by naclander** [comment]
That would only really work for one particular, but my Circe is set up such that all nicks get a random(?) color assigned to them. The `circe-highlight-all-nicks-face` would have to constantly change. Also, I think that would affect all other highlighted nicks no?

I think instead of `circe-highlight-all-nicks-face`, we need a per-nick face, of the same color as the one used to highlight the nick on every line.

**Comment by wasamasa** [comment]
I don't get what you're referring to then.  I do know that `circe-highlight-all-nicks` highlights every nick with `circe-highlight-all-nicks-face`, something that doesn't fit together with your description of every nick receiving a different color.  This is the behavior `circe-color-nicks` which includes the ability of highlighting nick inside messages as well.  Are you possibly mistaking one for the other?

**Comment by naclander** [comment]
Its possible I'm confusing some variables, so I'll try and illustrate what I mean with a picture:

https://i.imgur.com/aKqUvsr.png

We see the nicks on the left of users speaking, those have different colors. When those nicks are mentioned in messages, I want those nicks to be highlighted in the same color as they are on the left, not a default green color. 

If this is already possible, I appreciate an explanation and maybe we should update some documentation regarding this.

**Comment by wasamasa** [comment]
The screenshot looks as if you have both enabled, so fix that first.  You'll want one or the other, but not both at the same time.

**Comment by naclander** [comment]
When I disable `circe-highlight-all-nicks` the nicks in messages aren't highlighted ( that's why I assumed `circe-highlight-all-nicks` was for ). Is there a separate thing I need to configure to highlight nicks in messages ( while not enabling `circe-highlight-all-nicks`) ?

**Comment by wasamasa** [comment]
Yes, you'll need to customize `circe-color-nicks-everywhere`.

**Comment by naclander** [comment]
`(setq circe-color-nicks-everywhere t)` seemed to do exactly what I wanted. 

So really the only problem I see is that 

`circe-color-nicks-everywhere` and `circe-highlight-all-nicks` seem to do similiar but very different things, and the names don't really give an indication of what those are. Maybe a more user friendly design choice would be for `circe-color-nicks-everwhere` to control whether the nicks are highlighted **and** in what color? Maybe it should be more clear that these two variables should are mutually exclusive? Thoughts?

**Comment by wasamasa** [comment]
That doesn't make any sense whatsoever. `circe-color-nicks` and `circe-highlight-all-nicks` are Circe modules, by definition they're expected to do different things.  It's unfortunate that `circe-highlight-all-nicks` happened first and is strictly less powerful than the second as newbies keep finding it and wonder whether Circe has the ability for coloring nicks in different colors at all.  It would most likely be better for it to be deprecated in favor of `circe-color-nicks`, however doing so would break the setup of everyone preferring `circe-highlight-all-nicks`.  `circe-color-nicks-everywhere` is a customizable for `circe-color-nicks` (as indicated by the common prefix), so it makes sense that it affects how the `circe-color-nicks` module operates.  You seem to be thoroughly confused about what they are, I suggest you to take at least a cursory look at their source files.

**Comment by naclander** [comment]
From a user of the package, I don't think we should expect the variables and module names to speak for themselves. I think the fact that I was confused is a good indication that other people can be too. 

I don't have a strong opinion what the solution is, I was just stating the the current state of affairs is confusing. And while I think its great emacs makes it really easy to dive in to the source, I don't think we should excuse bad UX by telling people to RTFM.

**Comment by jorgenschaefer** [comment]
Thanks for the report. I fully agree that this is confusing and we really should get rid of either `circe-color-nicks.el` or `circe-highlight-all-nicks.el` – I just don't know which, as I use neither :-D Does one include the functionality of the other completely maybe? I'm very open to ideas.

**Comment by wasamasa** [comment]
@jorgenschaefer You can emulate `circe-highlight-all-nicks` by using `circe-color-nicks` with a pool of one element, so that should be settled.

**Comment by jorgenschaefer** [comment]
Does that solve this problem? :-)

**Comment by naclander** [comment]
That looks good. Not sure if there is any documentation that needs to be updated. Thanks!
