### ISSUE TITLE
sentinel test failing on linux

### ISSUE THREAD

**Issue by dunn** [emacs-circe/circe#338]
I'm getting this locally on Debian, as well as in Travis: https://travis-ci.org/dunn/homebrew-emacs/jobs/375098617#L959
```
The `irc--sentinel' function
  should emit conn.failed for a failed event
  should emit conn.connected on an open event
  should emit conn.disconnected for a broken connection
  should emit conn.disconnected for a finished process
  should emit conn.disconnected for an exiting process
  should ignored killed processes
  should ignore deleted processes
  should raise an error for unknown events  FAILED
```

**Comment by jorgenschaefer** [comment]
Weird. Seems to work for us?

**Comment by dunn** [comment]
That's an async test, right? Is there a way to raise the timeout, so I can check if that's the issue?

**Comment by jorgenschaefer** [comment]
Nope, not an async test. `M-: (irc--sentinel 'proc "bla bla\n")` should raise an error.

**Comment by dunn** [comment]
Yeah, that works in isolation for me too.  Very strange; I'll poke at it some more.

**Comment by wasamasa** [comment]
No such error in the CI, therefore I'm closing this one.
