### ISSUE TITLE
[Feature Request] Previous Input History

### ISSUE THREAD

**Issue by naclander** [emacs-circe/circe#339]
Similar to shell mode `comint-previous-input`, it would be cool if I could recall previous things I wrote in circe so that I could potentially type them again.

I searched whether this feature was available but couldn't find anything useful.

**Comment by jorgenschaefer** [comment]
Did you try `M-p` and `M-n` (like in comint)?

**Comment by wasamasa** [comment]
Closing since M-p and M-n provide this.
