### ISSUE TITLE
color nicks on logs ?

### ISSUE THREAD

**Issue by pseudomyne** [emacs-circe/circe#351]
Hi ! 
Is there any known way to get nicks colored when browsing through circe logs ? 
Any minor-mode ?
Thank you

**Comment by wasamasa** [comment]
There is no such thing, no, you'd need to extend the lui-logging module for that. That aside, how exactly do you want colors to get there? Currently it's just plain text, there's at least the following options:

- Log in a format recognized by pygments, then view logs through pygmentize with IRC highlighting
- Emit ANSI escapes and view the file in a terminal (or a buffer set up to translate these)
- Use enriched-mode to store the faces along with the text
- Write HTML with inline CSS

**Comment by pseudomyne** [comment]
Thanks for the answer, wasamasa. I need a bit of research to fully understand what you say :)
I think I just want nicks to be coloured everywhere..

**Comment by wasamasa** [comment]
Another solution I've discovered recently: https://stevelosh.com/blog/2021/03/small-common-lisp-cli-programs/#s8-case-study-a-batch-coloring-utility

I've ported the batchcolor project to Scheme in an evening. Porting it to Emacs Lisp should take even less time.
