### ISSUE TITLE
debugging connection to irc twich server

### ISSUE THREAD

**Issue by yashasolutions** [emacs-circe/circe#403]
Hi,

Context: 
I am struggling with the configuration of circe for twitch irc server. 
The following config keep giving me ` -Server- _ Improperly formatted auth` however I have tested these parameters with other clients, it worked. And I have circe working fine with Libera chat, so I am wondering what is the problem here, and what is really being sent to the server

```elisp
(after! circe
  (set-irc-server!
    "irc.chat.twitch.tv"
    `(:tls t
      :port 6697
      :host "irc.chat.twitch.tv"
      :nick "mytwitchusername"
      :sasl-username "mytwitchusername"
      :sasl-password "oauth:xxxxxxxxxxxxxxxxxxxxxx"
      :channels ( "#somechan")))
  )
```

My issue: 
is there a way to have a log of the actual commands sent to the server and the raw response of the server?

**Comment by wasamasa** [comment]
Evaluate `(setq irc-debug-log t)` and inspect the resulting IRC log buffer.
