### ISSUE TITLE
circe-user definition

### ISSUE THREAD

**Issue by yashasolutions** [emacs-circe/circe#404]
Hi,

I have some issue to connect to a server requiring authentication.

Config has 
```elisp
(setq circe-default-user "yashasolutions")
```
and in the server definition:
```elisp
:sasl-username "yashasolutions"
```

But log is when checking the log I see
```
C: NICK yashasolutions
C: USER yashasolutions 8 * yashasolutions
```

Not sure how to interpret this, but it does look like it's different from the config, right? Am I doing something incorrect?

**Comment by wasamasa** [comment]
```elisp
(defun irc-send-USER (conn user mode realname)
  "Send a USER message for registration.

MODE should be an integer as per RFC 2812"
  (irc-send-command conn "USER" user (format "%s" mode) "*" realname))
```

The client is sending the USER message which consists of the user, mode and realname. The meaning of the user mode is explained in the mentioned RFC. So, nothing unusual going on there. I'd recommend you to compare IRC logs between circe and another client where authentication works.
