### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by jonasstein** [emacs-circe/circe#408]
Please tag a new release, if possible.

Initial user request on Gentoo bug tracker: https://bugs.gentoo.org/839897
Thank you

**Comment by wasamasa** [comment]
Thanks for the reminder. I looked into how exactly the release process works and released 2.12.

**Comment by rahilarious** [comment]
> Thanks for the reminder. I looked into how exactly the release process works and released 2.12.

Thank you <3
